### ISSUE TITLE
charm goes to error state - hook failed: "config-changed"

### ISSUE THREAD

**Issue by marosg42** [canonical/grafana-k8s-operator#130]
### Bug Description

During deployment as part of cos-lite we encountered
```
Model  Controller              Cloud/Region      Version  SLA          Timestamp
cos    foundations-kubernetes  kubernetes_cloud  2.9.34   unsupported  16:01:10Z

App           Version  Status   Scale  Charm             Channel  Rev  Address         Exposed  Message
alertmanager           waiting    0/1  alertmanager-k8s  edge      31  10.152.183.89   no       installing agent
grafana                waiting      1  grafana-k8s       edge      43  10.152.183.121  no       installing agent
loki                   waiting      1  loki-k8s          edge      45  10.152.183.225  no       installing agent
prometheus             waiting      1  prometheus-k8s    edge      71  10.152.183.154  no       installing agent
traefik                waiting      1  traefik-k8s       edge      87  10.246.167.235  no       installing agent

Unit             Workload  Agent  Address          Ports  Message
alertmanager/0*  unknown   lost                           agent lost, see 'juju show-status-log alertmanager/0'
grafana/0*       error     idle   192.168.252.133         hook failed: "config-changed"
loki/0*          waiting   idle                           Waiting for resource limit patch to apply
prometheus/0*    waiting   idle   192.168.252.134         Waiting for resource limit patch to apply
traefik/0*       waiting   idle   192.168.254.7           waiting for service: 'traefik'
```

### To Reproduce

This was a failure in SQA unattended deployment, we deploy cos-lite with edge channel

### Environment

This was a failure in SQA unattended deployment, we deploy cos-lite with edge channel

### Relevant log output

```shell
No way to catch logs as the deployments are constantly replaced in SQA.
Here is a link to artifacts
https://oil-jenkins.canonical.com/artifacts/4dd077fa-63bf-4d76-83d1-5a573d974790/index.html

juju crashdump for cos is https://oil-jenkins.canonical.com/artifacts/4dd077fa-63bf-4d76-83d1-5a573d974790/generated/generated/cos/juju-crashdump-cos-2022-09-26-16.01.25.tar.gz
```

### Additional context

This was a failure in SQA unattended deployment, we deploy cos-lite with edge channel

**Comment by simskij** [comment]
This seems to be the relevant part of the debug logs:

```
unit-grafana-0: 2022-09-26 16:01:05 ERROR unit.grafana/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/usr/lib/python3.8/urllib/request.py", line 1354, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/var/lib/juju/agents/unit-grafana-0/charm/venv/ops/pebble.py", line 246, in connect
    self.sock.connect(self.socket_path)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-grafana-0/charm/venv/ops/pebble.py", line 1553, in _request_raw
    response = self.opener.open(request, timeout=self.timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/var/lib/juju/agents/unit-grafana-0/charm/venv/ops/pebble.py", line 260, in http_open
    return self.do_open(_UnixSocketConnection, req,  # type:ignore
  File "/usr/lib/python3.8/urllib/request.py", line 1357, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 2] No such file or directory>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./src/charm.py", line 1142, in <module>
    main(GrafanaCharm, use_juju_for_storage=True)
  File "/var/lib/juju/agents/unit-grafana-0/charm/venv/ops/main.py", line 438, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-grafana-0/charm/venv/ops/main.py", line 150, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-grafana-0/charm/venv/ops/framework.py", line 355, in emit
    framework._emit(event)  # noqa
  File "/var/lib/juju/agents/unit-grafana-0/charm/venv/ops/framework.py", line 848, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-grafana-0/charm/venv/ops/framework.py", line 923, in _reemit
    custom_handler(event)
  File "./src/charm.py", line 234, in _on_config_changed
    self._configure_replication()
  File "./src/charm.py", line 280, in _configure_replication
    self.containers["replication"].get_plan().services
  File "/var/lib/juju/agents/unit-grafana-0/charm/venv/ops/model.py", line 1490, in get_plan
    return self._pebble.get_plan()
  File "/var/lib/juju/agents/unit-grafana-0/charm/venv/ops/pebble.py", line 1845, in get_plan
    resp = self._request('GET', '/v1/plan', {'format': 'yaml'})
  File "/var/lib/juju/agents/unit-grafana-0/charm/venv/ops/pebble.py", line 1515, in _request
    response = self._request_raw(method, path, query, headers, data)
  File "/var/lib/juju/agents/unit-grafana-0/charm/venv/ops/pebble.py", line 1566, in _request_raw
    raise ConnectionError(e.reason)
ops.pebble.ConnectionError: [Errno 2] No such file or directory
```
