### ISSUE TITLE
`Uncaught exception` in grafana_dashboard.py on a JSON dashboard

### ISSUE THREAD

**Issue by simondeziel** [canonical/grafana-k8s-operator#175]
### Bug Description

Feeding the [LXD dashboard](https://grafana.com/grafana/dashboards/15726-lxd/) to Grafana using the `lib/charms/grafana_k8s/v0/grafana_dashboard.py` lib crashes with an `uncaught exception`.

### To Reproduce

1. `juju deploy -m cos cos-lite --trust --overlay ./offers-overlay.yaml --overlay ./storage-small-overlay.yaml`
2. `juju integrate -m test lxd:grafana-dashboard-k8s grafana-dashboards:grafana-dashboard`

### Environment

The juju controller is on a LXD container, the COS-Lite bundle is deployed in a model called `cos` running on a microk8s instance. The dashboard providing charm (LXD) runs in a different model called `test`.

### Relevant log output

```shell
unit-grafana-0: 21:19:52 ERROR unit.grafana/0.juju-log grafana-dashboard:36: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "./src/charm.py", line 1156, in <module>
    main(GrafanaCharm, use_juju_for_storage=True)
  File "/var/lib/juju/agents/unit-grafana-0/charm/venv/ops/main.py", line 438, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-grafana-0/charm/venv/ops/main.py", line 150, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-grafana-0/charm/venv/ops/framework.py", line 355, in emit
    framework._emit(event)  # noqa
  File "/var/lib/juju/agents/unit-grafana-0/charm/venv/ops/framework.py", line 856, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-grafana-0/charm/venv/ops/framework.py", line 931, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-grafana-0/charm/lib/charms/grafana_k8s/v0/grafana_dashboard.py", line 1272, in _on_grafana_dashboard_relation_changed
    changes = self._render_dashboards_and_signal_changed(event.relation)
  File "/var/lib/juju/agents/unit-grafana-0/charm/lib/charms/grafana_k8s/v0/grafana_dashboard.py", line 1369, in _render_dashboards_and_signal_changed
    content = _convert_dashboard_fields(content, inject_dropdowns)
  File "/var/lib/juju/agents/unit-grafana-0/charm/lib/charms/grafana_k8s/v0/grafana_dashboard.py", line 599, in _convert_dashboard_fields
    dict_content = _replace_template_fields(dict_content, datasources, existing_templates)
  File "/var/lib/juju/agents/unit-grafana-0/charm/lib/charms/grafana_k8s/v0/grafana_dashboard.py", line 633, in _replace_template_fields
    if panel["datasource"].lower() in replacements.values():
AttributeError: 'dict' object has no attribute 'lower'
```
```


### Additional context

Here's the `juju status` output of the `cos` model:

```
$ juju status -m cos --relations
Model  Controller  Cloud/Region            Version  SLA          Timestamp
cos    overlord    microk8s-cos/localhost  3.0.2    unsupported  21:15:30Z

App           Version  Status  Scale  Charm             Channel  Rev  Address         Exposed  Message
alertmanager  0.23.0   active      1  alertmanager-k8s  stable    36  10.152.183.244  no       
catalogue              active      1  catalogue-k8s     stable     4  10.152.183.93   no       
grafana       9.2.1    active      1  grafana-k8s       stable    52  10.152.183.229  no       
loki          2.4.1    active      1  loki-k8s          stable    47  10.152.183.104  no       
prometheus    2.33.5   active      1  prometheus-k8s    stable    79  10.152.183.182  no       
traefik                active      1  traefik-k8s       stable    93  172.17.33.1     no       

Unit             Workload  Agent  Address       Ports  Message
alertmanager/0*  active    idle   10.1.134.123         
catalogue/0*     active    idle   10.1.134.110         
grafana/0*       active    idle   10.1.134.126         
loki/0*          active    idle   10.1.134.117         
prometheus/0*    active    idle   10.1.134.122         
traefik/0*       active    idle   10.1.134.113         

Offer                            Application   Charm             Rev  Connected  Endpoint              Interface                Role
alertmanager-karma-dashboard     alertmanager  alertmanager-k8s  36   0/0        karma-dashboard       karma_dashboard          provider
grafana-dashboards               grafana       grafana-k8s       52   0/0        grafana-dashboard     grafana_dashboard        requirer
loki-logging                     loki          loki-k8s          47   0/0        logging               loki_push_api            provider
prometheus-receive-remote-write  prometheus    prometheus-k8s    79   0/0        receive-remote-write  prometheus_remote_write  provider
prometheus-scrape                prometheus    prometheus-k8s    79   0/0        metrics-endpoint      prometheus_scrape        requirer

Relation provider                   Requirer                     Interface              Type     Message
alertmanager:alerting               loki:alertmanager            alertmanager_dispatch  regular  
alertmanager:alerting               prometheus:alertmanager      alertmanager_dispatch  regular  
alertmanager:grafana-dashboard      grafana:grafana-dashboard    grafana_dashboard      regular  
alertmanager:grafana-source         grafana:grafana-source       grafana_datasource     regular  
alertmanager:replicas               alertmanager:replicas        alertmanager_replica   peer     
alertmanager:self-metrics-endpoint  prometheus:metrics-endpoint  prometheus_scrape      regular  
catalogue:catalogue                 alertmanager:catalogue       catalogue              regular  
catalogue:catalogue                 grafana:catalogue            catalogue              regular  
catalogue:catalogue                 prometheus:catalogue         catalogue              regular  
grafana:grafana                     grafana:grafana              grafana_peers          peer     
grafana:metrics-endpoint            prometheus:metrics-endpoint  prometheus_scrape      regular  
loki:grafana-dashboard              grafana:grafana-dashboard    grafana_dashboard      regular  
loki:grafana-source                 grafana:grafana-source       grafana_datasource     regular  
loki:metrics-endpoint               prometheus:metrics-endpoint  prometheus_scrape      regular  
prometheus:grafana-dashboard        grafana:grafana-dashboard    grafana_dashboard      regular  
prometheus:grafana-source           grafana:grafana-source       grafana_datasource     regular  
prometheus:prometheus-peers         prometheus:prometheus-peers  prometheus_peers       peer     
traefik:ingress                     alertmanager:ingress         ingress                regular  
traefik:ingress                     catalogue:ingress            ingress                regular  
traefik:ingress-per-unit            loki:ingress                 ingress_per_unit       regular  
traefik:ingress-per-unit            prometheus:ingress           ingress_per_unit       regular  
traefik:metrics-endpoint            prometheus:metrics-endpoint  prometheus_scrape      regular  
traefik:traefik-route               grafana:ingress              traefik_route          regular
```

**Comment by simondeziel** [comment]
This has been fixed in `edge` as the datasource can now be a `dict`. This makes sense because our Grafana dashboard was exported from Grafana 9.x.
