### ISSUE TITLE
[grafana-source] Uncaught exception on relation departed

### ISSUE THREAD

**Issue by sed-i** [canonical/grafana-k8s-operator#232]
### Bug Description

Removing grafana results in a traceback.

### To Reproduce

1. Relate grafana to prometheus.
2. Remove grafana.

### Environment

```
Model        Controller  Cloud/Region        Version  SLA          Timestamp
welcome-k8s  microk8s    microk8s/localhost  3.2.0    unsupported  22:49:08-04:00

App   Version  Status      Scale  Charm                     Channel  Rev  Address         Message
graf  9.2.1    terminated    0/1  grafana-k8s                          1  10.152.183.123  unit stopped by the cloud
prom  2.44.0   active          1  prometheus-k8s            edge     134  10.152.183.234
```

### Relevant log output

```shell
unit-graf-0: 22:45:28.955 ERROR unit.graf/0.juju-log grafana-source:81: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "./src/charm.py", line 1280, in <module>
    main(GrafanaCharm, use_juju_for_storage=True)
  File "/var/lib/juju/agents/unit-graf-0/charm/venv/ops/main.py", line 441, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-graf-0/charm/venv/ops/main.py", line 149, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-graf-0/charm/venv/ops/framework.py", line 344, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-graf-0/charm/venv/ops/framework.py", line 833, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-graf-0/charm/venv/ops/framework.py", line 922, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-graf-0/charm/lib/charms/grafana_k8s/v0/grafana_source.py", line 615, in _on_grafana_source_relation_departed
    removed_source = self._remove_source_from_datastore(event)
  File "/var/lib/juju/agents/unit-graf-0/charm/lib/charms/grafana_k8s/v0/grafana_source.py", line 630, in _remove_source_from_datastore
    stored_sources = self.get_peer_data("sources")
  File "/var/lib/juju/agents/unit-graf-0/charm/lib/charms/grafana_k8s/v0/grafana_source.py", line 733, in get_peer_data
    data = self._charm.peers.data[self._charm.app].get(key, "")  # type: ignore[attr-defined]
AttributeError: 'NoneType' object has no attribute 'data'
unit-graf-0: 22:45:29.204 ERROR juju.worker.uniter.operation hook "grafana-source-relation-departed" (via hook dispatching script: dispatch) failed: exit status 1
```

**Comment by sed-i** [comment]
Duplicate of https://github.com/canonical/grafana-k8s-operator/issues/138.
Updated https://bugs.launchpad.net/juju/+bug/1998282.
Closing.
