### ISSUE TITLE
hook failed: "grafana-source-relation-departed"

### ISSUE THREAD

**Issue by markbeierl** [canonical/grafana-k8s-operator#281]
### Bug Description

Deployed cos lite bundle to a model and had it running for several days.  Attempted to destroy the model, and grafana agent went into error status with `hook failed: "grafana-source-relation-departed"`

### To Reproduce

1. juju add-model cos microk8s
2. juju deploy cos-lite --trust
3. juju deploy cos-configuration-k8s \
  --config git_repo=https://github.com/canonical/sdcore-cos-configuration \
  --config git_branch=main \
  --config git_depth=1 \
  --config grafana_dashboards_path=grafana_dashboards/sdcore/
4. juju integrate cos-configuration-k8s grafana

I then performed cross model integrations with two other models on offer cos.prometheus:receive-remote-write and cos.loki:logging.

The first model, I performed a destroy model, however the second still remained with a relation.

I then destroyed the cos-lite model and this error occurred.

### Environment

```
juju      3.1.6          24626  3.1/stable          canonical✓  -
microk8s  v1.27.7        6101   1.27-strict/stable  canonical✓  -
```

### Relevant log output

```shell
unit-grafana-0: 16:59:34 INFO juju.worker.uniter awaiting error resolution for "relation-departed" hook
unit-grafana-0: 16:59:35 ERROR unit.grafana/0.juju-log grafana-source:13: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "./src/charm.py", line 1312, in <module>
    main(GrafanaCharm, use_juju_for_storage=True)
  File "/var/lib/juju/agents/unit-grafana-0/charm/venv/ops/main.py", line 441, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-grafana-0/charm/venv/ops/main.py", line 149, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-grafana-0/charm/venv/ops/framework.py", line 344, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-grafana-0/charm/venv/ops/framework.py", line 841, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-grafana-0/charm/venv/ops/framework.py", line 930, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-grafana-0/charm/lib/charms/grafana_k8s/v0/grafana_source.py", line 613, in _on_grafana_source_relation_departed
    removed_source = self._remove_source_from_datastore(event)
  File "/var/lib/juju/agents/unit-grafana-0/charm/lib/charms/grafana_k8s/v0/grafana_source.py", line 628, in _remove_source_from_datastore
    stored_sources = self.get_peer_data("sources")
  File "/var/lib/juju/agents/unit-grafana-0/charm/lib/charms/grafana_k8s/v0/grafana_source.py", line 731, in get_peer_data
    data = self._charm.peers.data[self._charm.app].get(key, "")  # type: ignore[attr-defined]
AttributeError: 'NoneType' object has no attribute 'data'
unit-grafana-0: 16:59:35 ERROR juju.worker.uniter.operation hook "grafana-source-relation-departed" (via hook dispatching script: dispatch) failed: exit status 1
```

**Comment by markbeierl** [comment]
Next resolve --no-retry gives
```
unit-grafana-0: 17:16:34 ERROR unit.grafana/0.juju-log grafana-dashboard:23: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "./src/charm.py", line 1312, in <module>
    main(GrafanaCharm, use_juju_for_storage=True)
  File "/var/lib/juju/agents/unit-grafana-0/charm/venv/ops/main.py", line 441, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-grafana-0/charm/venv/ops/main.py", line 149, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-grafana-0/charm/venv/ops/framework.py", line 344, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-grafana-0/charm/venv/ops/framework.py", line 841, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-grafana-0/charm/venv/ops/framework.py", line 930, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-grafana-0/charm/lib/charms/grafana_k8s/v0/grafana_dashboard.py", line 1390, in _on_grafana_dashboard_relation_broken
    self._remove_all_dashboards_for_relation(event.relation)
  File "/var/lib/juju/agents/unit-grafana-0/charm/lib/charms/grafana_k8s/v0/grafana_dashboard.py", line 1524, in _remove_all_dashboards_for_relation
    if self._get_stored_dashboards(relation.id):
  File "/var/lib/juju/agents/unit-grafana-0/charm/lib/charms/grafana_k8s/v0/grafana_dashboard.py", line 1557, in _get_stored_dashboards
    return self.get_peer_data("dashboards").get(str(relation_id), {})
  File "/var/lib/juju/agents/unit-grafana-0/charm/lib/charms/grafana_k8s/v0/grafana_dashboard.py", line 1572, in get_peer_data
    data = self._charm.peers.data[self._charm.app].get(key, "")  # type: ignore[attr-defined]
AttributeError: 'NoneType' object has no attribute 'data'
unit-grafana-0: 17:16:34 ERROR juju.worker.uniter.operation hook "grafana-dashboard-relation-broken" (via hook dispatching script: dispatch) failed: exit status 1
```

**Comment by markbeierl** [comment]
Two more resolves and
```
unit-grafana-0: 17:17:56 ERROR unit.grafana/0.juju-log metrics-endpoint:20: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "./src/charm.py", line 1312, in <module>
    main(GrafanaCharm, use_juju_for_storage=True)
  File "/var/lib/juju/agents/unit-grafana-0/charm/venv/ops/main.py", line 441, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-grafana-0/charm/venv/ops/main.py", line 149, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-grafana-0/charm/venv/ops/framework.py", line 344, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-grafana-0/charm/venv/ops/framework.py", line 841, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-grafana-0/charm/venv/ops/framework.py", line 930, in _reemit
    custom_handler(event)
  File "./src/charm.py", line 370, in _maybe_provision_own_dashboard
    self.init_dashboard_provisioning(dashboards_dir_path)
  File "./src/charm.py", line 521, in init_dashboard_provisioning
    self._configure()
  File "./src/charm.py", line 436, in _configure
    if self._check_datasource_provisioning():
  File "./src/charm.py", line 403, in _check_datasource_provisioning
    grafana_datasources = self._generate_datasource_config()
  File "./src/charm.py", line 1023, in _generate_datasource_config
    for source_info in self.source_consumer.sources:
  File "/var/lib/juju/agents/unit-grafana-0/charm/lib/charms/grafana_k8s/v0/grafana_source.py", line 707, in sources
    stored_sources = self.get_peer_data("sources")
  File "/var/lib/juju/agents/unit-grafana-0/charm/lib/charms/grafana_k8s/v0/grafana_source.py", line 731, in get_peer_data
    data = self._charm.peers.data[self._charm.app].get(key, "")  # type: ignore[attr-defined]
AttributeError: 'NoneType' object has no attribute 'data'
unit-grafana-0: 17:17:56 ERROR juju.worker.uniter.operation hook "metrics-endpoint-relation-broken" (via hook dispatching script: dispatch) failed: exit status 1
```

**Comment by PietroPasotti** [comment]
Issue is that the peer relation is apparently removed before the grafana-source one. So when the charm lib does `self._charm.peers`, which does `self.model.get_relation(PEER)`, it gets a None.
Solution: add guards in front of all `self._charm.peers` calls to early-exit if there is no peer relation (which hopefully only ever happens if the charm is being nuked)

**Comment by phvalguima** [comment]
Seeing this issue on grafana `latest/stable`, revision 113

**Comment by Abuelodelanada** [comment]
In a chat with @gaborbk in [Matrix](https://matrix.to/#/!nHXpRkcSNJHlHdUGbQ:ubuntu.com/$3do0Lbk9ViF7rcHkhBKvjuwIUX669xZVrm1JPEMUrlU?via=ubuntu.com&via=matrix.org) we also see this issue on grafana `latest/stable`, revision 117

As far as I understand the issue is in fact in [this method](https://github.com/canonical/grafana-k8s-operator/blob/main/lib/charms/grafana_k8s/v0/grafana_dashboard.py#L1558):

```python
    def _get_stored_dashboards(self, relation_id: int) -> list:
        """Pull stored dashboards out of the peer data bucket."""
        return self.get_peer_data("dashboards").get(str(relation_id), {})
```

`relation_id` is `None` because we are calling this method from `_remove_all_dashboards_for_relation`. That method is called in the context of a `relation-broken` event where relation data [can no longer be read-written](https://juju.is/docs/sdk/relation-name-relation-broken-event).


```log
unit-grafana-0: 16:03:38 DEBUG unit.grafana/0.juju-log grafana-dashboard:176: Emitting Juju event grafana_dashboard_relation_broken.
unit-grafana-0: 16:03:38 WARNING unit.grafana/0.juju-log grafana-dashboard:176: 'app' expected but not received.
unit-grafana-0: 16:03:38 WARNING unit.grafana/0.juju-log grafana-dashboard:176: 'app_name' expected in snapshot but not found.
unit-grafana-0: 16:03:38 ERROR unit.grafana/0.juju-log grafana-dashboard:176: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "./src/charm.py", line 1542, in <module>
    main(GrafanaCharm, use_juju_for_storage=True)
  File "/var/lib/juju/agents/unit-grafana-0/charm/venv/ops/main.py", line 548, in main
    manager.run()
  File "/var/lib/juju/agents/unit-grafana-0/charm/venv/ops/main.py", line 527, in run
    self._emit()
  File "/var/lib/juju/agents/unit-grafana-0/charm/venv/ops/main.py", line 516, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-grafana-0/charm/venv/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-grafana-0/charm/venv/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-grafana-0/charm/venv/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-grafana-0/charm/venv/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-grafana-0/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 543, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-grafana-0/charm/lib/charms/grafana_k8s/v0/grafana_dashboard.py", line 1391, in _on_grafana_dashboard_relation_broken
    self._remove_all_dashboards_for_relation(event.relation)
  File "/var/lib/juju/agents/unit-grafana-0/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 543, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-grafana-0/charm/lib/charms/grafana_k8s/v0/grafana_dashboard.py", line 1525, in _remove_all_dashboards_for_relation
    if self._get_stored_dashboards(relation.id):
  File "/var/lib/juju/agents/unit-grafana-0/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 543, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-grafana-0/charm/lib/charms/grafana_k8s/v0/grafana_dashboard.py", line 1558, in _get_stored_dashboards
    return self.get_peer_data("dashboards").get(str(relation_id), {})
  File "/var/lib/juju/agents/unit-grafana-0/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 543, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-grafana-0/charm/lib/charms/grafana_k8s/v0/grafana_dashboard.py", line 1573, in get_peer_data
    data = self._charm.peers.data[self._charm.app].get(key, "")  # type: ignore[attr-defined]
AttributeError: 'NoneType' object has no attribute 'data'
unit-grafana-0: 16:03:38 ERROR juju.worker.uniter.operation hook "grafana-dashboard-relation-broken" (via hook dispatching script: dispatch) failed: exit status 1
```

**Comment by Abuelodelanada** [comment]
This issue is related to this fix in Juju 3.5.5:

https://bugs.launchpad.net/juju/+bug/1998282

**Comment by gaborbk** [comment]
Thank you for finding the fix @Abuelodelanada - sounds like my only option is tiupgrade Juju version to 3.5.5+

**Comment by sed-i** [comment]
Likely fixed in #383 (rev134+).

**Comment by Abuelodelanada** [comment]
Probably fixed by:

- https://github.com/canonical/grafana-k8s-operator/pull/383
- https://github.com/canonical/grafana-k8s-operator/pull/293

Please, feel free to re-open if not the case
